[project]
name = "github-action"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "flake8>=7.3.0",
    "pandas>=2.3.1",
    "pytest>=8.4.1",
]
